// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  chunkId: __t.u64().primaryKey().name("chunk_id"),
  status: __t.string(),
  assignedNode: __t.option(__t.identity()).name("assigned_node"),
  tileX: __t.u32().name("tile_x"),
  tileY: __t.u32().name("tile_y"),
  minRe: __t.f64().name("min_re"),
  maxRe: __t.f64().name("max_re"),
  minIm: __t.f64().name("min_im"),
  maxIm: __t.f64().name("max_im"),
  width: __t.u32(),
  height: __t.u32(),
  maxIterations: __t.u32().name("max_iterations"),
  pixelData: __t.option(__t.string()).name("pixel_data"),
  updatedAtMicros: __t.u64().name("updated_at_micros"),
});
