// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  cols: __t.u32(),
  rows: __t.u32(),
  maxIterations: __t.u32().name("max_iterations"),
  reMin: __t.f64().name("re_min"),
  reMax: __t.f64().name("re_max"),
  imMin: __t.f64().name("im_min"),
  imMax: __t.f64().name("im_max"),
  imageWidth: __t.u32().name("image_width"),
  imageHeight: __t.u32().name("image_height"),
  updatedAtMicros: __t.u64().name("updated_at_micros"),
});
