// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  chunkId: __t.u64().primaryKey().name("chunk_id"),
  taskId: __t.u32().name("task_id"),
  status: __t.string(),
  assignedNode: __t.option(__t.identity()).name("assigned_node"),
  rowStart: __t.u32().name("row_start"),
  rowEnd: __t.u32().name("row_end"),
  colStart: __t.u32().name("col_start"),
  colEnd: __t.u32().name("col_end"),
  tileResultJson: __t.option(__t.string()).name("tile_result_json"),
  updatedAtMicros: __t.u64().name("updated_at_micros"),
});
