// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  taskId: __t.u32().name("task_id"),
  aRows: __t.u32().name("a_rows"),
  aCols: __t.u32().name("a_cols"),
  bCols: __t.u32().name("b_cols"),
  tileSize: __t.u32().name("tile_size"),
  matrixAJson: __t.string().name("matrix_a_json"),
  matrixBJson: __t.string().name("matrix_b_json"),
  resultJson: __t.option(__t.string()).name("result_json"),
  status: __t.string(),
  updatedAtMicros: __t.u64().name("updated_at_micros"),
});
