// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  pinLength: __t.u32().name("pin_length"),
  targetHash: __t.string().name("target_hash"),
  totalCandidates: __t.u32().name("total_candidates"),
  chunkSize: __t.u32().name("chunk_size"),
  pinFound: __t.option(__t.string()).name("pin_found"),
  foundByNode: __t.option(__t.identity()).name("found_by_node"),
  startedAtMicros: __t.u64().name("started_at_micros"),
  foundAtMicros: __t.option(__t.u64()).name("found_at_micros"),
  updatedAtMicros: __t.u64().name("updated_at_micros"),
});
