// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  chunkId: __t.u64().primaryKey().name("chunk_id"),
  status: __t.string(),
  assignedNode: __t.option(__t.identity()).name("assigned_node"),
  rangeStart: __t.u32().name("range_start"),
  rangeEnd: __t.u32().name("range_end"),
  pinLength: __t.u32().name("pin_length"),
  targetHash: __t.string().name("target_hash"),
  foundPin: __t.option(__t.string()).name("found_pin"),
  updatedAtMicros: __t.u64().name("updated_at_micros"),
});
