// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  cols: __t.u32(),
  rows: __t.u32(),
  maxIterations: __t.u32(),
  reMin: __t.f64(),
  reMax: __t.f64(),
  imMin: __t.f64(),
  imMax: __t.f64(),
};