// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const GridConfig = __t.object("GridConfig", {
  id: __t.u32(),
  taskId: __t.u32(),
  cols: __t.u32(),
  rows: __t.u32(),
  maxIterations: __t.u32(),
  reMin: __t.f64(),
  reMax: __t.f64(),
  imMin: __t.f64(),
  imMax: __t.f64(),
  imageWidth: __t.u32(),
  imageHeight: __t.u32(),
  updatedAtMicros: __t.u64(),
});
export type GridConfig = __Infer<typeof GridConfig>;

export const MandelbrotChunkQueue = __t.object("MandelbrotChunkQueue", {
  chunkId: __t.u64(),
  taskId: __t.u32(),
  status: __t.string(),
  assignedNode: __t.option(__t.identity()),
  tileX: __t.u32(),
  tileY: __t.u32(),
  minRe: __t.f64(),
  maxRe: __t.f64(),
  minIm: __t.f64(),
  maxIm: __t.f64(),
  width: __t.u32(),
  height: __t.u32(),
  maxIterations: __t.u32(),
  pixelData: __t.option(__t.string()),
  updatedAtMicros: __t.u64(),
});
export type MandelbrotChunkQueue = __Infer<typeof MandelbrotChunkQueue>;

export const MatrixChunkQueue = __t.object("MatrixChunkQueue", {
  chunkId: __t.u64(),
  taskId: __t.u32(),
  status: __t.string(),
  assignedNode: __t.option(__t.identity()),
  rowStart: __t.u32(),
  rowEnd: __t.u32(),
  colStart: __t.u32(),
  colEnd: __t.u32(),
  tileResultJson: __t.option(__t.string()),
  updatedAtMicros: __t.u64(),
});
export type MatrixChunkQueue = __Infer<typeof MatrixChunkQueue>;

export const MatrixJobConfig = __t.object("MatrixJobConfig", {
  id: __t.u32(),
  taskId: __t.u32(),
  aRows: __t.u32(),
  aCols: __t.u32(),
  bCols: __t.u32(),
  tileSize: __t.u32(),
  matrixAJson: __t.string(),
  matrixBJson: __t.string(),
  resultJson: __t.option(__t.string()),
  status: __t.string(),
  updatedAtMicros: __t.u64(),
});
export type MatrixJobConfig = __Infer<typeof MatrixJobConfig>;

export const NodeStatus = __t.object("NodeStatus", {
  nodeId: __t.identity(),
  donatedChunks: __t.u64(),
  lastSeenMicros: __t.u64(),
});
export type NodeStatus = __Infer<typeof NodeStatus>;

export const PinChunkQueue = __t.object("PinChunkQueue", {
  chunkId: __t.u64(),
  taskId: __t.u32(),
  status: __t.string(),
  assignedNode: __t.option(__t.identity()),
  rangeStart: __t.u32(),
  rangeEnd: __t.u32(),
  pinLength: __t.u32(),
  targetHash: __t.string(),
  foundPin: __t.option(__t.string()),
  updatedAtMicros: __t.u64(),
});
export type PinChunkQueue = __Infer<typeof PinChunkQueue>;

export const PinCrackConfig = __t.object("PinCrackConfig", {
  id: __t.u32(),
  taskId: __t.u32(),
  pinLength: __t.u32(),
  targetHash: __t.string(),
  totalCandidates: __t.u32(),
  chunkSize: __t.u32(),
  pinFound: __t.option(__t.string()),
  foundByNode: __t.option(__t.identity()),
  startedAtMicros: __t.u64(),
  foundAtMicros: __t.option(__t.u64()),
  updatedAtMicros: __t.u64(),
});
export type PinCrackConfig = __Infer<typeof PinCrackConfig>;

export const Task = __t.object("Task", {
  taskId: __t.u32(),
  taskKey: __t.string(),
  displayName: __t.string(),
  isActive: __t.bool(),
  requestHelp: __t.bool(),
  updatedAtMicros: __t.u64(),
});
export type Task = __Infer<typeof Task>;

