// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ChunkQueue = __t.object("ChunkQueue", {
  chunkId: __t.u64(),
  status: __t.string(),
  assignedNode: __t.option(__t.identity()),
  tileX: __t.u32(),
  tileY: __t.u32(),
  minRe: __t.f64(),
  maxRe: __t.f64(),
  minIm: __t.f64(),
  maxIm: __t.f64(),
  width: __t.u32(),
  height: __t.u32(),
  maxIterations: __t.u32(),
  pixelData: __t.option(__t.string()),
  updatedAtMicros: __t.u64(),
});
export type ChunkQueue = __Infer<typeof ChunkQueue>;

export const GridConfig = __t.object("GridConfig", {
  id: __t.u32(),
  cols: __t.u32(),
  rows: __t.u32(),
  maxIterations: __t.u32(),
  reMin: __t.f64(),
  reMax: __t.f64(),
  imMin: __t.f64(),
  imMax: __t.f64(),
  imageWidth: __t.u32(),
  imageHeight: __t.u32(),
  updatedAtMicros: __t.u64(),
});
export type GridConfig = __Infer<typeof GridConfig>;

export const NodeStatus = __t.object("NodeStatus", {
  nodeId: __t.identity(),
  donatedChunks: __t.u64(),
  lastSeenMicros: __t.u64(),
});
export type NodeStatus = __Infer<typeof NodeStatus>;

export const PinChunkQueue = __t.object("PinChunkQueue", {
  chunkId: __t.u64(),
  status: __t.string(),
  assignedNode: __t.option(__t.identity()),
  rangeStart: __t.u32(),
  rangeEnd: __t.u32(),
  pinLength: __t.u32(),
  targetHash: __t.string(),
  foundPin: __t.option(__t.string()),
  updatedAtMicros: __t.u64(),
});
export type PinChunkQueue = __Infer<typeof PinChunkQueue>;

export const PinCrackConfig = __t.object("PinCrackConfig", {
  id: __t.u32(),
  pinLength: __t.u32(),
  targetHash: __t.string(),
  totalCandidates: __t.u32(),
  chunkSize: __t.u32(),
  pinFound: __t.option(__t.string()),
  foundByNode: __t.option(__t.identity()),
  startedAtMicros: __t.u64(),
  foundAtMicros: __t.option(__t.u64()),
  updatedAtMicros: __t.u64(),
});
export type PinCrackConfig = __Infer<typeof PinCrackConfig>;

