// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import HeartbeatReducer from "../heartbeat_reducer";
import RequestWorkReducer from "../request_work_reducer";
import ResetGridReducer from "../reset_grid_reducer";
import SubmitResultReducer from "../submit_result_reducer";

export type HeartbeatParams = __Infer<typeof HeartbeatReducer>;
export type RequestWorkParams = __Infer<typeof RequestWorkReducer>;
export type ResetGridParams = __Infer<typeof ResetGridReducer>;
export type SubmitResultParams = __Infer<typeof SubmitResultReducer>;

