// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import HeartbeatReducer from "../heartbeat_reducer";
import RequestWorkReducer from "../request_work_reducer";
import ResetGridReducer from "../reset_grid_reducer";
import ResetPinCrackReducer from "../reset_pin_crack_reducer";
import ResetTaskReducer from "../reset_task_reducer";
import SetTaskActiveReducer from "../set_task_active_reducer";
import SetTaskHelpReducer from "../set_task_help_reducer";
import SubmitMatrixJobReducer from "../submit_matrix_job_reducer";
import SubmitResultReducer from "../submit_result_reducer";

export type HeartbeatParams = __Infer<typeof HeartbeatReducer>;
export type RequestWorkParams = __Infer<typeof RequestWorkReducer>;
export type ResetGridParams = __Infer<typeof ResetGridReducer>;
export type ResetPinCrackParams = __Infer<typeof ResetPinCrackReducer>;
export type ResetTaskParams = __Infer<typeof ResetTaskReducer>;
export type SetTaskActiveParams = __Infer<typeof SetTaskActiveReducer>;
export type SetTaskHelpParams = __Infer<typeof SetTaskHelpReducer>;
export type SubmitMatrixJobParams = __Infer<typeof SubmitMatrixJobReducer>;
export type SubmitResultParams = __Infer<typeof SubmitResultReducer>;

